language: java
jdk:
  - oraclejdk8

#kivéve, hogy ne küldjön másnak üzenetet a build-elés eredményéről
#notifications:
#  slack: ftsrg:ecvIo6H1l9zFO7qSwf3Juz3U
#  on_success: change
#  on_failure: always
