language: java
jdk:
  - oraclejdk8
addons:
  sonarqube:
    organization: "iet-homework-team"
    token:
      secure: "KEiZlUuvIA3g6IwHtXXrLu+EzBGJWoYYrFhqcDgn4vjiANtUhiyeLZYCEBw/ACHpQF9CpDu2ycJDawhGgxnMNkRQnNfB+XqvPIzbYxoxAjqAaL6KRFD22HImxxJqCYQtEKS7NY/OoH18DoGiieB5haOIfSpwYjcJPOPE3KvIJqfCCAUUTCGk9+qDXc0sW9RDrBpURsd+L9+7cKaq2faExnsY0OzNfiSSJj4su3m5VTBY7/Qf0Iz0qDaB/e8KQmjj/fqvB4ooDn3SSaprUVWYg/mS/vbQ1cU21zczdCuTL83+dk6k6/qnFKenPxqNsgGb3xXbz0Hs5hEnn4OnPi8B2pM9TPPWq4fj9XyuehvT8nyZMEb9zAx9cqhDfi4jKTju0LvphJ/86QgLCdzcoEp0LHBnTGibe8nt8Xp6fqgyQ998tqTvkQNa0dZiiTnJoGqA86RLsFDUjingDvdIf7OLpeGp073yfLoB52eT4/JNFlh+EugjGwn+B50cFy168ltlRy4VnnO4PtqSomsnUtCX3HVtw5EpNDWuJMVYGjxNHRpQID9fRjsh8SNti0wiPUzDLNGo1VAKNSMo+TIOS0r9P1E7JcHr3r7kQ1gTmkkTED56yyGzwFdd7/CXEsd9MwACMJNWpLGn3vPJBAwzpqV/MwC7raq+pwlbzxjBQA+f6FU="
script:
  - ./gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)